/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
id INT GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(255) NOT NULL,
date_of_birth DATE,
escape_attempts INT,
neutered BOOLEAN,
weight_kg DECIMAL,
PRIMARY KEY (id)
);

ALTER TABLE animals
ADD species VARCHAR(255);

CREATE TABLE owners (
id INT GENERATED BY DEFAULT AS IDENTITY,
full_name VARCHAR(255) NOT NULL,
age INT,
PRIMARY KEY (id)
);

CREATE TABLE species (
id INT GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

ALTER TABLE animals
DROP species;

ALTER TABLE animals ADD COLUMN species_id INT REFERENCES species(id);

ALTER TABLE animals ADD COLUMN owners_id INT REFERENCES owners(id);
