/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
id INT GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(255) NOT NULL,
date_of_birth DATE,
escape_attempts INT,
neutered BOOLEAN,
weight_kg DECIMAL,
PRIMARY KEY (id)
);

ALTER TABLE animals
ADD species VARCHAR(255);

CREATE TABLE owners (
id INT GENERATED BY DEFAULT AS IDENTITY,
full_name VARCHAR(255) NOT NULL,
age INT,
PRIMARY KEY (id)
);

CREATE TABLE species (
id INT GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

ALTER TABLE animals
DROP species;

ALTER TABLE animals ADD COLUMN species_id INT REFERENCES species(id);

ALTER TABLE animals ADD COLUMN owners_id INT REFERENCES owners(id);

----------------------Day-4-Project--------------------------------

CREATE TABLE vets (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    age INT CHECK (age > 0 AND age < 130),
    date_of_graduation DATE,
    PRIMARY KEY (id)
);

CREATE TABLE specializations (
species_id INT REFERENCES species(id),
vets_id INT REFERENCES vets(id)
);

CREATE TABLE visits (
animals_id INT REFERENCES animals(id),
vets_id INT REFERENCES vets(id)
);